init:
  - git config --global core.autocrlf true

build_script:
  - build.cmd

artifacts:
  - path: 'artifacts\build\*.nupkg'
    name: NuGet Packages

branches:
  only:
    - master
    - develop

environment:
  DNX_BUILD_VERSION: $(APPVEYOR_BUILD_NUMBER)